module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primaryDark: "#4F3E47",
        secondaryDark: "#878696",
        light: "#F4F4F0",
        beigeLight: "#E4D3CC",
        beige: "#DAB8B3",
        pinkLight: "#D89CA5",
        pinkDark: "#B56770",
        pinkMedium: "#B88083",
        pinkPale: "#BE9092",
        pinkSoft: "#CDA9AB",
        peach: "#FDE0DA",
      },
    },
    fontFamily: {
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
    },
  },
};
